### ISSUE TITLE
サイドバーの画面実装の作成

### ISSUE THREAD

**Issue by Taku3939** [sls-training/2023-rails-sample#54]
# やること

ページ遷移するためのサイドバーを作成する

`/admin/users` : これから作成するユーザ管理用ページのルーティング

※以前チュートリアルで作成したヘッダーのスタイリングがbootstrapのアップグレードを行ったことによって壊れてしまったので作成し直しています。

※ルーティングについては`/admin/users`以外についてはチュートリアルで作成済みのページ

## 表示条件
- 未ログイン : 左
- ログイン済み(管理者ユーザでない場合) : 中央
- ログイン済み(管理者ユーザの場合) : 右

## 画面レイアウトと遷移先

画面レイアウト

![スクリーンショット 2023-05-26 16 20 32](https://github.com/sls-training/2023-rails-sample/assets/53074461/07bd7f7e-cb33-4428-b8ec-cf7b68685485)

サイドバー
<img width="594" alt="スクリーンショット 2023-05-26 18 07 18" src="https://github.com/sls-training/2023-rails-sample/assets/53074461/36f805f3-d014-4ac3-adb8-471bb03840f3">

## 備考

- なぜヘッダーではなくサイドバーにしたのか
  項目が多くなってきてこちらの方が一覧性高くなると考えました + 作ってみたかったから

**Comment by tim-toga** [comment]
サインインじゃなくて、サインアップの間違い？

他は良さそう。

**Comment by tk0miya** [comment]
管理者の画面がいくつかあるなら `/console` ではなく、もう 1階層深くしたいですね。
また、管理者っぽさを出すために `/admin` にするのもよさそうです。

ということで `/admin/users` とかはどうでしょうか
